### ISSUE TITLE
Hack Font for Linux

### ISSUE THREAD

**Issue by rjorge99** [pyrho/hack-font-ligature-nerd-font#2]
Hi, I installed the font in windows and works great. But in Ubuntu, it appears without ligature. Is there anything to do to make it work in Linux? Thanks

**Comment by pyrho** [comment]
Hey,

I use this on Linux and macOS so it should work. 

Afaik some terminal emulators don’t support ligatures (like Alacritty), I use [Kitty](https://github.com/kovidgoyal/kitty) which allows ligatures by default.
